kind: KubeProxyConfiguration
apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: 0.0.0.0
metricsBindAddress: 0.0.0.0:10249
clientConnection:
  kubeconfig: /etc/kubernetes/conf/kube-proxy.kubeconfig
hostnameOverride: node2
clusterCIDR: 10.254.0.0/16
